version: "3.3"

services:
  mysql:
    image: mysql:5
    # restart: always
    environment:
      - MYSQL_DAT=itsurvivors
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - 3307:3307
    volumes:
      - "./:/var/lib/mysql"
