version: "3.3"

services:
  db-mysql:
    image: mysql:5
    # restart: always
    environment:
      - MYSQL_DATABASE=itsurvivors
      - MYSQL_USER=proyect
      - MYSQL_ROOT_PASSWORD=proyect123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - "./mysql_data:/var/lib/mysql"
